name: Release Workflow Artifacts
on:
  workflow_call:

    inputs: 
      artifacts:
        description: 'List of workflow artifacts split by ` ` (space) characters, e.g., `"GlamorousToolkit-x86_64-apple-darwin.app.zip GlamorousToolkit-x86_64-pc-windows-msvc.zip"`, that should be uploaded as an existing or new version'
        required: true
        type: string
      version: 
        description: 'Version under which artifacts should be uploaded. If "bump" is set, a new version will be released.'
        required: false
        default: "bump"
        type: string

    outputs:
      version: 
        description: 'Release version, e.g., `v0.1.42`'
        value: ${{ jobs.Release.outputs.version }}

    secrets:
      release_token: 
        description: 'GitHub token value with release and upload permissions.'
        required: true

env:
  GTOOLKIT_VM_DIR: 'gtoolkit-vm'
  APP_LIBRARIES_VERSIONS: 'libraries.version'

jobs:
  Release: 
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.variables.outputs.version }}

    env: 
      TARGET: 'x86_64-unknown-linux-gnu'

    steps: 

      - name: Define Environment Variables
        id: environment
        run: |
          if [ -z "${{ inputs.version }}" -o "${{ inputs.version }}" = "bump" ]; then
            echo "Feenk Releaser will create a new version (git tag)."
            echo "::set-output name=bump_version::true"
          else
            echo "Feenk Releaser will use an existing version (git tag): ${{ inputs.version }}."
            echo "::set-output name=bump_version::false"
          fi

      - name: Debug bump_version
        run: |
          echo "The steps.environment.bump_version value is: '${{ steps.environment.bump_version }}'"

      - name: Debug bump_version == true
        run: |
          echo "The inputs.version value is '${{ inputs.version }}'."
          if [ ( ! -z "${{ inputs.version }}" ) -o ( ! "${{ inputs.version }}" = "bump" ) ]; then
            echo "ERROR: The inputs.version value must be empty or bump" >&2
            exit 2
          fi
        if: ${{ steps.environment.bump_version == true }}

      - name: Debug bump_version == false
        run: |
          echo "The inputs.version value is '${{ inputs.version }}'."
          if [ -z "${{ inputs.version }}" -o "${{ inputs.version }}" = "bump" ]; then
            echo "ERROR: The inputs.version value must be a version" >&2
            exit 1
          fi
        if: ${{ steps.environment.bump_version == false }}

      - name: Checkout Repository Code
        uses: actions/checkout@v2 

      - name: Checkout GToolkit VM Repository Code
        uses: feenkcom/gtoolkit-custom-app/.github/actions/checkout-gtoolkit-vm@main

      - name: Define Repository Name
        shell: bash
        run: |
          REPOSITORY_NAME="$(echo ${{ github.repository }} | sed -n -e 's@^[^/]*/\([^/]*\)@\1@p')"
          echo REPOSITORY_NAME=${REPOSITORY_NAME} >> $GITHUB_ENV
          echo REPOSITORY_NAME=${REPOSITORY_NAME}
          REPOSITORY_OWNER="${{ github.repository_owner }}"
          echo REPOSITORY_OWNER=${REPOSITORY_OWNER} >> $GITHUB_ENV
          echo REPOSITORY_OWNER=${REPOSITORY_OWNER}

      - name: Download All VM Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ env.GTOOLKIT_VM_DIR }}

      - name: Display Files
        working-directory: ${{ env.GTOOLKIT_VM_DIR }}
        run: |
          ls -la
          ls -la *.zip

      - name: Download Feenk Releaser
        shell: bash
        working-directory: ${{ env.GTOOLKIT_VM_DIR }}
        run: |
          wget -O feenk-releaser https://github.com/feenkcom/releaser-rs/releases/download/${{ env.FEENK_RELEASER_VERSION }}/feenk-releaser-${{ env.TARGET }}
          chmod +x feenk-releaser

      - name: Release As New Version
        env: 
          GITHUB_TOKEN: ${{ secrets.release_token }}
        working-directory: ${{ env.GTOOLKIT_VM_DIR }}
        run: |
          ./feenk-releaser \
            --owner ${{ env.REPOSITORY_OWNER }} \
            --repo ${{ env.REPOSITORY_NAME }} \
            --token GITHUB_TOKEN \
            --bump minor \
            --auto-accept \
            --assets ${{ inputs.artifacts }}
          echo FEENK_RELEASE_VERSION=bump >> $GITHUB_ENV
        if: ${{ steps.environment.bump_version == true }}
      
      - name: Release Into Existing Version
        env: 
          GITHUB_TOKEN: ${{ secrets.release_token }}
        working-directory: ${{ env.GTOOLKIT_VM_DIR }}
        run: |
          ./feenk-releaser \
            --owner ${{ env.REPOSITORY_OWNER }} \
            --repo ${{ env.REPOSITORY_NAME }} \
            --token GITHUB_TOKEN \
            --version ${{ inputs.version }} \
            --auto-accept \
            --assets ${{ inputs.artifacts }}
          echo FEENK_RELEASE_VERSION=${{ inputs.version }} >> $GITHUB_ENV
        if: ${{ steps.environment.bump_version == false }}

      # At this moment, it does NOT return right values for bump versions
      - name: Define Job Outputs
        id: variables
        run: |
          echo "::set-output name=version::${{ env.FEENK_RELEASE_VERSION }}"
